# permissions for end users to view transports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transport-viewer-role
rules:
- apiGroups:
  - planes.chickensushi.ch
  resources:
  - transports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - planes.chickensushi.ch
  resources:
  - transports/status
  verbs:
  - get
